### ISSUE TITLE
force closes instantly on latest beta Android N on Nexus 6p

### ISSUE THREAD

**Issue by dimitrieh** [dulleh/akhyou#50] opened 2016-06-16 10:46 UTC
It immediately closes, and asks to reset the app.. then nothing happens or changes

good app apart from the force closing! keep up the good work;)

**Comment by yoshinatsu** [comment] 2016-06-16 13:06
Same here on 5.1.1

**Comment by yoshinatsu** [comment] 2016-06-16 13:16
After clearing the app's data, it booted fine. But I lost my bookmarked series.

**Comment by dulleh** [comment] 2016-06-16 21:18
Duplicate of #46. As has been mentioned, clearing app data will fix it.

**Closed by dulleh** 2016-06-16 21:18 UTC
