### ISSUE TITLE
"Error: Trying to evoke virtual message"

### ISSUE THREAD

**Issue by xersace** [dulleh/akhyou#30] opened 2016-02-21 05:15 UTC
I am experiencing this error while trying to watch anime. It is a constant error.

I am on my OnePlus One, thank you for all the support.

**Comment by dulleh** [comment] 2016-02-21 13:09
I have never seen this before :O

Could you post a screenshot? Is there a specific action that causes it to occur?

**Comment by xersace** [comment] 2016-02-21 16:40
It happens when I happen to favorite anime and it also happens whe n I try
to watch and episode from a list of anime. Also the new KissAnime section
you added gives me the "retry" message, even though there is a series that
is in their catalog.

http://imgur.com/1zY1K27
http://imgur.com/h7S2WVX

By the way, thank for for making this app! It is absolutely beautiful and I
use it everyday. The previous versions of this app were working perfectly
but I can't watch anything on this version!

**Comment by dulleh** [comment] 2016-02-21 20:50
Thanks, I'll try to get it working soon!

**Comment by xersace** [comment] 2016-02-21 21:25
Thank you so much!

**Comment by dulleh** [comment] 2016-02-22 22:20
> Also the new KissAnime section you added gives me the "retry" message, even though there is a series that is in their catalog.

Should be fixed as of 292c9ac825ec00cfeb8f4ee3680d010921169b21.

The favorites is hard to replicate so you'll have to bear with it for now, sorry.

Since this is now only an issue with favourites, it is a duplicate of #21 so time to close.

**Closed by dulleh** 2016-02-22 22:20 UTC

**Comment by xersace** [comment] 2016-02-22 23:38
Yess! Thank you Dulleh! Everything is working perfectly!

**Comment by dulleh** [comment] 2016-02-22 23:39
Glad it worked! Enjoy ^^
